name: Deploy Lambda via Docker

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: petrol-predictor-lambda # Change to your ECR Repository Name
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update All Lambda Functions
        run: |
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/petrol-predictor-lambda:latest"
          aws lambda update-function-code --function-name servo_data --image-uri $IMAGE_URI

    
          # Update Lambda 2
          aws lambda update-function-code --function-name market_data --image-uri $IMAGE_URI
          aws lambda wait function-updated --function-name market_data
          aws lambda update-function-configuration \
           --function-name market_data \
           --image-config '{"Command":["data.market.market_data_lambda.lambda_handler"]}'

          # Update Lambda 3
          aws lambda update-function-code --function-name station_geo --image-uri $IMAGE_URI
          aws lambda wait function-updated --function-name station_geo
          aws lambda update-function-configuration \
           --function-name station_geo \
           --image-config '{"Command":["data.servo_saver.append_station_geo_lambda.lambda_handler"]}'

      - name: Wait for updates to complete
        run: |
          aws lambda wait function-updated --function-name servo_data
          aws lambda wait function-updated --function-name market_data
          aws lambda wait function-updated --function-name station_geo
          
      - name: Update Lambda environment variables
        env:
          SERVO_SAVER_API: ${{ secrets.SERVO_SAVER_API }}
          AURORA_DB: ${{ secrets.AURORA_DB }}
          AURORA_ENDPOINT: ${{ secrets.AURORA_ENDPOINT }}
          AURORA_USER: ${{ secrets.AURORA_USER }}
          REGION: ${{ secrets.REGION }}
        run: |
          aws lambda update-function-configuration \
            --function-name servo_data \
            --environment "Variables={SERVO_SAVER_API=$SERVO_SAVER_API,AURORA_DB=$AURORA_DB,AURORA_ENDPOINT=$AURORA_ENDPOINT,AURORA_USER=$AURORA_USER,REGION=$REGION}"

          aws lambda update-function-configuration \
            --function-name market_data \
            --environment "Variables={AURORA_DB=$AURORA_DB,AURORA_ENDPOINT=$AURORA_ENDPOINT,AURORA_USER=$AURORA_USER,REGION=$REGION}"

          aws lambda update-function-configuration \
            --function-name station_geo \
            --environment "Variables={AURORA_DB=$AURORA_DB,AURORA_ENDPOINT=$AURORA_ENDPOINT,AURORA_USER=$AURORA_USER,REGION=$REGION}"
